<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>GVPT722 - Interactions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="..//files/img/hex-testudo.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../html/custom.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">GVPT722</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../content/01-introduction.html" rel="" target="" aria-current="page">
 <span class="menu-text">Content</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../content/05-interactions.html">Interactions</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../content/01-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linear Regression: A Refresher</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../content/02-ols_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">OLS Basics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../content/03-statistical_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical Inference</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../content/04-model_specification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple Linear Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../content/05-interactions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Interactions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../content/04-panel_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Panel Data</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#set-up" id="toc-set-up" class="nav-link active" data-scroll-target="#set-up">Set up</a></li>
  <li><a href="#exporting-mass-destruction" id="toc-exporting-mass-destruction" class="nav-link" data-scroll-target="#exporting-mass-destruction">Exporting mass destruction</a></li>
  <li><a href="#dual-use-trade" id="toc-dual-use-trade" class="nav-link" data-scroll-target="#dual-use-trade">Dual-use trade</a></li>
  <li><a href="#are-these-effects-significant" id="toc-are-these-effects-significant" class="nav-link" data-scroll-target="#are-these-effects-significant">Are these effects significant?</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Interactions</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>THIS IS A DRAFT.</p>
</div>
</div>
<section id="set-up" class="level2">
<h2 class="anchored" data-anchor-id="set-up">Set up</h2>
<p>You will need to install a new package to follow along:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"car"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You then need to load all relevant packages into your R session:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(polisciols)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modelsummary)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(marginaleffects)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exporting-mass-destruction" class="level2">
<h2 class="anchored" data-anchor-id="exporting-mass-destruction">Exporting mass destruction</h2>
<p>Trade between states is not only the product of economic considerations. States often promote or restrict trade with other states for political and security reasons. International political economists have identified a wide range of political factors that shape international trade, including regime type (democracies tend to trade more with each other than with other regimes), instability (states tend to trade less with states they believe to be at a high risk of conflict), and alliances (trade tends to “follow the flag”).</p>
<p>These theories of the political determinants of trade flows are often agnostic to the good being traded. But this is not necessarily the case. It is reasonable to expect that a state will be more mindful of who it supplies javelin missiles to than to whom it sells typewriters. <span class="citation" data-cites="fuhrmann2008">Fuhrmann (<a href="#ref-fuhrmann2008" role="doc-biblioref">2008</a>)</span> explores this distinction explicitly in his paper <em>Exporting Mass Destruction? The Determinants of Dual-Use Trade</em>.</p>
<p>He seeks to identify the strategic determinants of trade in dual-use commodities. These are commodities that can be used to produce Weapons of Mass Destruction (WMDs) or in legitimate civilian applications. Unlike javelin missiles, the purpose to which importing states will put these commodities is not clear. How do exporters balance the benefits of trade against the risk that they may enable WMD manufacturing?</p>
<p>To explore this question, Fuhrmann analyzes exports of dual-use commodities from the US to all other countries in the post-Cold War period between 1991 and 2001. Whilst he explores both economic and political determinants, his focus is on whether or not the US and its trade partner share the same foreign policy goals.</p>
<p>Before we dive into his full model, let’s set up our expectations. We should expect that states will be more reticent to sell these sensitive commodities to their enemies. Who knows to what nefarious purpose they may put them to?</p>
<p>Fuhrmann uses the degree to which states share similar foreign policy platforms to identify friends and enemies. This variable, <code>pol_dissimiliarity</code> is binary and takes on a value of <code>1</code> if the country enacts foreign policies that are very dissimilar to those of the US. In other words, <code>pol_dissimilarity = 1</code> when they are enemies.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>For those who are interested, he asks whether the average compatibility between the country’s and the United States’ foreign policy between 1991 and 2001 was in the lowest 10th percentile of all countries’ similarities with the United States.</p>
</div>
</div>
<p>So, we should expect that the US traded less in these sensitive commodities with its enemies than with its friends. Let’s take a look:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>x_mass_destruction <span class="sc">|&gt;</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(pol_dissimilarity) <span class="sc">|&gt;</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avg_x_dual_use =</span> scales<span class="sc">::</span><span class="fu">dollar</span>(<span class="fu">mean</span>(x_dual_use)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  pol_dissimilarity avg_x_dual_use
              &lt;dbl&gt; &lt;chr&gt;         
1                 0 $1,046,814,259
2                 1 $1,710,910,642</code></pre>
</div>
</div>
<p>Hmm, the US appears to have provided its enemies with more dual-use commodities than its friends! That’s not very strategic!</p>
<p>But wait, let’s not write off US foreign policy just yet. Dual-use commodities are sensitive because they can be used to produce or support WMDs. But not all countries that import these commodities pursue WMDs. Many need these commodities for civilian applications.</p>
<p>So, it may in fact be the case that the US is only reticent to sell dual-use commodities to enemies that it knows are pursuing or have access to WMDs. Let’s include this characteristic in our summary:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>x_mass_destruction <span class="sc">|&gt;</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(pol_dissimilarity, wmd_pursuit) <span class="sc">|&gt;</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avg_x_dual_use =</span> scales<span class="sc">::</span><span class="fu">dollar</span>(<span class="fu">mean</span>(x_dual_use))) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
# Groups:   pol_dissimilarity [2]
  pol_dissimilarity wmd_pursuit avg_x_dual_use
              &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;         
1                 0           0 $924,468,836  
2                 0           1 $3,004,341,034
3                 1           0 $1,811,301,875
4                 1           1 $104,650,927  </code></pre>
</div>
</div>
<p>Ah! There we go! The US is happy to trade in dual-use commodities with enemies when they are not pursuing WMDs. Further, the US is happy to trade in dual-use commodities with its friends that <em>are</em> pursuing WMDs. I guess their interests must be really aligned.</p>
<p>This simple summary suggests that the relationship between trade in dual-use commodities and foreign policy is not as straight forward as we first thought. The US appears to be less willing to trade in these sensitive commodities with enemies <em>if they are pursuing WMDs</em>. This condition is critical to understanding this relationship.</p>
<p>In other words, we cannot say anything about the relationship between trade in dual-use commodities and foreign policy without first knowing whether the country in question is pursuing WMDs. If someone were to ask you “do you think the US avoids exporting dual-use commodities to its enemies?”, you should reply “it depends!”.</p>
<p>We can explore this more complex relationship formally using <strong>interactions</strong>. Below, we will replicate Fuhrmann’s analysis. In doing do, we will strengthen our understanding of multiple linear regression and introduce the knowledge required to interpret interaction effects.</p>
<p>Let’s get started!</p>
</section>
<section id="dual-use-trade" class="level2">
<h2 class="anchored" data-anchor-id="dual-use-trade">Dual-use trade</h2>
<p>Fuhrmann draws on existing literature to build an understanding of the determinants of trade in dual-use commodities. Let’s build his baseline model of US exports of dual-use commodities:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(x_dual_use) <span class="sc">~</span> defence_ally <span class="sc">+</span> democracy <span class="sc">+</span> conflict <span class="sc">+</span> pol_dissimilarity <span class="sc">+</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>          wmd_pursuit <span class="sc">+</span> wmd_acquisition <span class="sc">+</span> log_gdp <span class="sc">+</span> log_population <span class="sc">+</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>          log_distance <span class="sc">+</span> log_x_all,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> x_mass_destruction)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">modelsummary</span>(m, </span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">stars =</span> T,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">coef_rename =</span> <span class="fu">c</span>(</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>               <span class="st">"log_gdp"</span> <span class="ot">=</span> <span class="st">"Average GDP (USD logged)"</span>,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>               <span class="st">"log_population"</span> <span class="ot">=</span> <span class="st">"Average population (logged)"</span>,</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>               <span class="st">"log_distance"</span> <span class="ot">=</span> <span class="st">"Distance between the United States and the country (logged)"</span>,</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>               <span class="st">"log_x_all"</span> <span class="ot">=</span> <span class="st">"Total imports from the US (USD logged)"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;(1)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">−3.085</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(3.173)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">defence_ally</td>
<td style="text-align: center;">0.244</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.545)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">democracy</td>
<td style="text-align: center;">0.837</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.526)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">conflict</td>
<td style="text-align: center;">−3.548***</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.928)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pol_dissimilarity</td>
<td style="text-align: center;">1.862**</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.604)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">wmd_pursuit</td>
<td style="text-align: center;">1.706*</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.771)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">wmd_acquisition</td>
<td style="text-align: center;">0.644</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.704)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Average GDP (USD logged)</td>
<td style="text-align: center;">0.289</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.210)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Average population (logged)</td>
<td style="text-align: center;">0.052</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.173)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Distance between the United States and the country (logged)</td>
<td style="text-align: center;">−0.033</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.177)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total imports from the US (USD logged)</td>
<td style="text-align: center;">0.616***</td>
</tr>
<tr class="even">
<td style="text-align: left; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(0.147)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: center;">151</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2</td>
<td style="text-align: center;">0.658</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R2 Adj.</td>
<td style="text-align: center;">0.634</td>
</tr>
<tr class="even">
<td style="text-align: left;">AIC</td>
<td style="text-align: center;">6080.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BIC</td>
<td style="text-align: center;">6116.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Log.Lik.</td>
<td style="text-align: center;">−317.663</td>
</tr>
<tr class="odd">
<td style="text-align: left;">F</td>
<td style="text-align: center;">26.973</td>
</tr>
<tr class="even">
<td style="text-align: left;">RMSE</td>
<td style="text-align: center;">1.98</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> + p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
<p>His argument focuses the level of political similarity between the US and its trade partner. Let’s look at the value of dual-use exports this model predicts friends and foes to receive:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_predictions</span>(m, <span class="at">condition =</span> <span class="st">"pol_dissimilarity"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="05-interactions_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="960"></p>
</div>
</div>
<p>As above, we see that countries with strongly dissimilar foreign policy agendas to the US receive the most dual-use exports from it. This runs counter to our expectations.</p>
<p>This model assumes that the association between exports in dual-use commodities and the level of compatibility between the trade partner’s and the United States’ foreign policy is constant across all trade partners regardless of their desire or capacity to produce WMDs. However, as Fuhrmann argues, this should not be the case: the US should be much more reticent to export dual-use commodities to states that are pursuing foreign policies that are not aligned with the US’s interests <em>and</em> seek to produce WMDs.</p>
<p>We can capture this by introducing into our model an interaction between dissimilarities and whether a state is pursuing acquiring nuclear, chemical, or biological weapons:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(x_dual_use) <span class="sc">~</span> defence_ally <span class="sc">+</span> democracy <span class="sc">+</span> conflict <span class="sc">+</span> pol_dissimilarity <span class="sc">+</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>          wmd_pursuit <span class="sc">+</span> wmd_acquisition <span class="sc">+</span> wmd_pursuit <span class="sc">*</span> pol_dissimilarity <span class="sc">+</span> log_gdp <span class="sc">+</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>          log_population <span class="sc">+</span> log_distance <span class="sc">+</span> log_x_all,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> x_mass_destruction)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">modelsummary</span>(m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&nbsp;(1)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">−2.823</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(3.149)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">defence_ally</td>
<td style="text-align: center;">0.276</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.540)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">democracy</td>
<td style="text-align: center;">0.872</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.522)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">conflict</td>
<td style="text-align: center;">−3.560</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.919)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pol_dissimilarity</td>
<td style="text-align: center;">2.163</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.620)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">wmd_pursuit</td>
<td style="text-align: center;">2.198</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.808)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">wmd_acquisition</td>
<td style="text-align: center;">0.574</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.698)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">log_gdp</td>
<td style="text-align: center;">0.273</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.208)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">log_population</td>
<td style="text-align: center;">0.055</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.172)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">log_distance</td>
<td style="text-align: center;">−0.040</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.175)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">log_x_all</td>
<td style="text-align: center;">0.620</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.145)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pol_dissimilarity × wmd_pursuit</td>
<td style="text-align: center;">−4.203</td>
</tr>
<tr class="even">
<td style="text-align: left; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(2.247)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: center;">151</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2</td>
<td style="text-align: center;">0.667</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R2 Adj.</td>
<td style="text-align: center;">0.640</td>
</tr>
<tr class="even">
<td style="text-align: left;">AIC</td>
<td style="text-align: center;">6078.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BIC</td>
<td style="text-align: center;">6117.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Log.Lik.</td>
<td style="text-align: center;">−315.787</td>
</tr>
<tr class="odd">
<td style="text-align: left;">F</td>
<td style="text-align: center;">25.276</td>
</tr>
<tr class="even">
<td style="text-align: left;">RMSE</td>
<td style="text-align: center;">1.96</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>To include an interaction in your <code>lm()</code> function, multiply the two variables together. Above, I included an interaction between <code>pol_dissimilarity</code> and <code>wmd_pursuit</code> by including <em>in addition to the two variables on their own</em> <code>pol_dissimilarity * wmd_pursuit</code>.</p>
<p>You must also include the <strong>constituative variables</strong> on their own. Above I included:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(<span class="fu">log</span>(x_dual_use) <span class="sc">~</span> ... <span class="sc">+</span> pol_dissimilarity <span class="sc">+</span> wmd_pursuit <span class="sc">+</span> wmd_pursuit <span class="sc">*</span> pol_dissimilarity, </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>   <span class="at">data =</span> x_mass_destruction)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<p>You need to be very careful when interpreting these coefficients. Let’s go through some of the important ones together.</p>
<p>One way to think about interactions is to look at the different regression lines for trade partners that are politically dissimilar and for those that are similar to the US.</p>
<p>Let’s start with the general regression function:</p>
<p><span class="math display">\[
Dual\ use\ exports = −2.82 + ... + 2.16 * pol\_dissimilarity + 2.20 * wmd\_pursuit - 4.20 pol\_dissimilarity * wmd\_pursuit + \epsilon
\]</span></p>
<p>Now, let’s look at this function for states that share the US’s foreign policy goals (<code>pol_dissimilarity = 0</code>):</p>
<p><span class="math display">\[
Dual\ use\ exports = −2.82 + ... + 2.16 * 0 + 2.20 * wmd\_pursuit - 4.20 * 0 * wmd\_pursuit + \epsilon
\]</span></p>
<p><span class="math display">\[
Dual\ use\ exports = −2.82 + ... + 2.20 * wmd\_pursuit + \epsilon
\]</span></p>
<p>And for states that are dissimilar to the US:</p>
<p><span class="math display">\[
Dual\ use\ exports = −2.82 + ... + 2.16 * 1 + 2.20 * wmd\_pursuit - 4.20 * 1 * wmd\_pursuit + \epsilon
\]</span></p>
<p><span class="math display">\[
Dual\ use\ exports = -0.66 - 2 * wmd\_pursuit + \epsilon
\]</span></p>
<p>So, among states that share the US’s political goals, pursuing WMDs actually increases their dual-use exports from the US relative to those like-minded states that do not pursue WMDs. We predict that the value of dual-use exports for these countries is -0.66 logged dollars, compared to −2.82 logged dollars among like-minded states that are not pursuing these weapons.</p>
<p>We can contrast this with our expectations among states that do not share the US’s political goals. When these states are pursuing WMDs, they receive -2.66 logged dollars of exports in these useful commodities from the US. As expected, this is less than that received by dissimilar states that are not pursuing these weapons (who we predict will receive -0.66 logged dollars in exports).</p>
<p>Let’s make this a little more tangible. Let’s find the average value of dual-use exports our model predicts friends and foes pursuring and not pursuing WMDs to receive:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(m) <span class="sc">|&gt;</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(pol_dissimilarity, wmd_pursuit) <span class="sc">|&gt;</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">pred_x_dual_use =</span> scales<span class="sc">::</span><span class="fu">dollar</span>(<span class="fu">exp</span>(<span class="fu">mean</span>(.fitted))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
# Groups:   pol_dissimilarity [2]
  pol_dissimilarity wmd_pursuit pred_x_dual_use
              &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;          
1                 0           0 $42,857,009    
2                 0           1 $401,105,513   
3                 1           0 $464,421,049   
4                 1           1 $104,650,927   </code></pre>
</div>
</div>
<p>Overall, the predicted effect of political dissimilarity is equal to:</p>
<p><span class="math display">\[
\beta_{pol\_dissimilarity} + \beta_{pol\_dissimilarity*wmd\_pursuit} * wmd\_pursuit = 2.16 - 4.20*wmd\_pursuit
\]</span></p>
<p>In other words: the effect on dual-use exports from the US of political dissimilarity <strong>depends</strong> on whether or not the trade partner is pursuing WMDs. Just as we theorized!</p>
<p>This also means that <span class="math inline">\(\beta_{pol\_dissimilarity}\)</span> represents the predicted effect of political dissimilarity <em>when the trade partner is not pursuing WMDs</em>.</p>
<p>Also, the predicted effect of pursuing WMDs is equal to:</p>
<p><span class="math display">\[
\beta_{wmd\_pursuit} + \beta_{pol\_dissimilarity*wmd\_pursuit} * pol\_dissimilarity = 2.20 - 4.20*wmd\_pursuit
\]</span></p>
<p>Again, the effect on dual-use exports from the US of pursuing WMDs <strong>depends</strong> on whether or not the trade partner is a friend or foe of the US.</p>
<p>The coefficient of the interaction term (<span class="math inline">\(\beta_{pol\_dissimilarity*wmd\_pursuit}\)</span>) is the effect of the effect. On the effect on dual-use exports from the US of political dissimilarity, it is the effect of the trade partner pursuing WMDs. On the effect on dual-use exports from the US of pursuing WMDs, it is the effect of being a friend or foe of the US.</p>
</section>
<section id="are-these-effects-significant" class="level2">
<h2 class="anchored" data-anchor-id="are-these-effects-significant">Are these effects significant?</h2>
<p>Remember, the predicted effect of political dissimilarity is equal to:</p>
<p><span class="math display">\[
\beta_{pol\_dissimilarity} + \beta_{pol\_dissimilarity*wmd\_pursuit} * wmd\_pursuit
\]</span></p>
<p>When the trade partner is not pursuing WMDs, the effect of political dissimilarity is equal to:</p>
<p><span class="math display">\[
\beta_{pol\_dissimilarity} + \beta_{pol\_dissimilarity*wmd\_pursuit} * 0 = \beta_{pol\_dissimilarity}
\]</span></p>
<p>Here, <span class="math inline">\(\beta_{pol\_dissimilarity}\)</span> is meaningful on its own. We can, therefore, use our familiar t-test (communicated through the p-value) to tell us whether the predicted effect of political dissimilarity on US dual-use exports to friends is significantly different from no effect.</p>
<p>Is the predicted effect of political dissimilarity on US dual-use exports among trade partners that pursue WMDs significant? To test this, we need to ask whether the joint effect is significantly different from zero:</p>
<p><span class="math display">\[
\beta_{pol\_dissimilarity} + \beta_{pol\_dissimilarity*wmd\_pursuit}
\]</span></p>
<p>In other words, you need to ask whether:</p>
<p><span class="math display">\[
\beta_{pol\_dissimilarity} = \beta_{pol\_dissimilarity*wmd\_pursuit} = 0
\]</span></p>
<p>We can use an <strong>F-test</strong> to formally test whether our coefficients are significantly different from zero.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(m, <span class="fu">c</span>(<span class="st">"pol_dissimilarity = 0"</span>, <span class="st">"pol_dissimilarity:wmd_pursuit = 0"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear hypothesis test

Hypothesis:
pol_dissimilarity = 0
pol_dissimilarity:wmd_pursuit = 0

Model 1: restricted model
Model 2: log(x_dual_use) ~ defence_ally + democracy + conflict + pol_dissimilarity + 
    wmd_pursuit + wmd_acquisition + wmd_pursuit * pol_dissimilarity + 
    log_gdp + log_population + log_distance + log_x_all

  Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)   
1    141 634.29                                
2    139 579.41  2    54.878 6.5826 0.001856 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The F-statistic for the joint hypothesis is 6.5826. The likelihood that we would get an F-statistic this large if, in fact, it was equal to zero is 0.001856. Therefore, we can reject the null hypothesis that both of these coefficients are equal to zero.</p>
<p>Therefore, we can say that the predicted effect of political dissimilarity on US dual-use exports among trade partners that pursue WMDs (<span class="math inline">\(\beta_{pol\_dissimilarity} + \beta_{pol\_dissimilarity*wmd\_pursuit} = 2.16 − 4.20\)</span>) is statistically significant.</p>
<p>Is the predicted effect of pursuing WMDs among friends statistically significant?</p>
<div class="callout callout-style-default callout-caution callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Remember, the predicted effect of pursuing WMDs is equal to:</p>
<p><span class="math display">\[
\beta_{wmd\_pursuit} + \beta_{pol\_dissimilarity*wmd\_pursuit} * pol\_dissimilarity
\]</span></p>
<p>When the trade partner is a friend, the effect of pursuing WMDs is equal to:</p>
<p><span class="math display">\[
\beta_{wmd\_pursuit} + \beta_{pol\_dissimilarity*wmd\_pursuit} * 0 = \beta_{wmd\_pursuit}
\]</span></p>
<p>So we can look at the statistical significance of that single coefficient. The p-value on <span class="math inline">\(\beta_{wmd\_pursuit}\)</span> is 0.007. This is statistically significant at the 0.05-level.</p>
</div>
</div>
</div>
<p>Is the predicted effect of pursuing WMDs among foes statistically significant?</p>
<div class="callout callout-style-default callout-caution callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>When the trade partner is a foe, the effect of pursuing WMDs is equal to:</p>
<p><span class="math display">\[
\beta_{wmd\_pursuit} + \beta_{pol\_dissimilarity*wmd\_pursuit}
\]</span></p>
<p>So we need to ask whether:</p>
<p><span class="math display">\[
\beta_{wmd\_pursuit} = \beta_{pol\_dissimilarity*wmd\_pursuit} = 0
\]</span></p>
<p>We can use an <strong>F-test</strong> to formally test whether our coefficients are significantly different from zero:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(m, <span class="fu">c</span>(<span class="st">"wmd_pursuit = 0"</span>, <span class="st">"pol_dissimilarity:wmd_pursuit = 0"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear hypothesis test

Hypothesis:
wmd_pursuit = 0
pol_dissimilarity:wmd_pursuit = 0

Model 1: restricted model
Model 2: log(x_dual_use) ~ defence_ally + democracy + conflict + pol_dissimilarity + 
    wmd_pursuit + wmd_acquisition + wmd_pursuit * pol_dissimilarity + 
    log_gdp + log_population + log_distance + log_x_all

  Res.Df    RSS Df Sum of Sq      F  Pr(&gt;F)  
1    141 614.78                              
2    139 579.41  2    35.373 4.2429 0.01627 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Again, we are very unlikely to see such a large F-statistic of 4.2429 (in fact, there is only a 1.63% chance) if it were zero. Therefore, we can state that the the effect of pursuing WMDs on dual-use exports from the US among its foes is statistically significant.</p>
</div>
</div>
</div>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-fuhrmann2008" class="csl-entry" role="listitem">
Fuhrmann, Matthew. 2008. <span>“Exporting Mass Destruction? The Determinants of Dual-Use Trade.”</span> <em>Journal of Peace Research</em> 45 (5): 633–52. <a href="https://www.jstor.org/stable/27640737">https://www.jstor.org/stable/27640737</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Content <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> 2024 by <a href="https://www.harrietgoers.com">Harriet Goers</a> <br> All content licensed under a <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> <i class="fa-brands fa-creative-commons-by" aria-label="creative-commons-by"></i> <i class="fa-brands fa-creative-commons-nc" aria-label="creative-commons-nc"></i> <a href="https://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-Non Commercial 4.0 International license (CC BY-NC 4.0)</a></div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">Made with <i class="fa-brands fa-r-project" aria-label="r-project"></i> and <a href="https://quarto.org/">Quarto</a><br> <a href="https://www.andrewheiss.com/teaching/">Heavily inspired by course websites built by Dr Andrew Heiss</a></div>
  </div>
</footer>



</body></html>